version: '3'
services:
  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:     
      - ./frontend:/app/
      - /app/node_modules      
    ports:
      - 8000:8000
    environment:
      VIRTUAL_HOST: frontend.dev
    networks:
      - fullstack 

  backend:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - ./backend:/app/
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      VIRTUAL_HOST: backend.dev
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge
      